/*
 * This program source code file is part of KiCad, a free EDA CAD application.
 *
 * Copyright The KiCad Developers, see AUTHORS.txt for contributors.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <widgets/chat_webview_panel.h>
#include <json_common.h>
#include <wx/log.h>
#include <wx/filename.h>
#include <kiplatform/ui.h>
#include <paths.h>

// Include the built React UI if available (generated by cmake)
#if __has_include("chat_ui_html.h")
#include "chat_ui_html.h"
#endif

CHAT_WEBVIEW_PANEL::CHAT_WEBVIEW_PANEL( wxWindow* aParent, wxWindowID aId ) :
    WEBVIEW_PANEL( aParent, aId ),
    m_bridgeReady( false )
{
    // Bind the loaded event so message handlers get registered
    BindLoadedEvent();
    
    // Register message handler for React -> C++ communication
    AddMessageHandler( wxT( "kicad" ), [this]( const wxString& msg ) {
        onBridgeMessage( msg );
    });
}


CHAT_WEBVIEW_PANEL::~CHAT_WEBVIEW_PANEL()
{
    ClearMessageHandlers();
}


void CHAT_WEBVIEW_PANEL::InitializeChatUI()
{
    wxWebView* browser = GetWebView();
    
    if( !browser )
        return;
    
    // Get the chat UI HTML file path using KiCad's standard data path
    wxFileName chatUiPath;
    chatUiPath.AssignDir( PATHS::GetStockDataPath() );
    chatUiPath.AppendDir( wxT( "resources" ) );
    chatUiPath.SetFullName( wxT( "chat-ui.html" ) );
    
    wxString fullPath = chatUiPath.GetFullPath();
    
    if( wxFileExists( fullPath ) )
    {
        // Load from file URL (this works better for complex JavaScript like React)
        wxString fileUrl = wxT( "file://" ) + fullPath;
        LoadURL( fileUrl );
    }
    else
    {
        // Fall back to embedded HTML via SetPage (may not work for complex JS)
        wxString html = GetChatUIHtml();
        SetPage( html );
    }
    
    // Theme will be set when bridge becomes ready (in onBridgeMessage)
}


void CHAT_WEBVIEW_PANEL::onBridgeMessage( const wxString& aMessage )
{
    try
    {
        nlohmann::json msg = nlohmann::json::parse( aMessage.ToStdString() );
        
        wxString type = wxString::FromUTF8( msg.value( "type", "" ) );
        
        if( type == wxT( "send_message" ) )
        {
            wxString content = wxString::FromUTF8( msg.value( "content", "" ) );
            
            // Check for bridge ready signal
            if( content == wxT( "__BRIDGE_READY__" ) )
            {
                m_bridgeReady.store( true );
                
                // Send initial theme immediately
                bool isDark = KIPLATFORM::UI::IsDarkTheme();
                wxString themeScript = wxString::Format(
                    wxT( "if(window.kichat){window.kichat.setTheme(%s);}" ),
                    isDark ? wxT( "true" ) : wxT( "false" )
                );
                RunScriptFireAndForget( themeScript );
                
                // Flush any pending commands that were queued before bridge was ready
                for( const wxString& cmd : m_pendingCommands )
                {
                    RunScriptFireAndForget( cmd );
                }
                m_pendingCommands.clear();
                return;
            }
            
            // Parse attachments if present
            std::vector<ChatAttachment> attachments;
            if( msg.contains( "attachments" ) && msg["attachments"].is_array() )
            {
                for( const auto& attJson : msg["attachments"] )
                {
                    ChatAttachment att;
                    att.name = wxString::FromUTF8( attJson.value( "name", "" ) );
                    att.mimeType = wxString::FromUTF8( attJson.value( "type", "" ) );
                    att.base64Data = wxString::FromUTF8( attJson.value( "data", "" ) );
                    att.size = attJson.value( "size", 0 );
                    attachments.push_back( att );
                }
            }
            
            if( m_sendMessageCallback && !content.IsEmpty() )
            {
                m_sendMessageCallback( content, attachments );
            }
        }
        else if( type == wxT( "stop_request" ) )
        {
            wxString tabId = wxString::FromUTF8( msg.value( "tabId", "" ) );
            if( m_stopRequestCallback )
            {
                m_stopRequestCallback( tabId );
            }
        }
        else if( type == wxT( "mode_changed" ) )
        {
            wxString mode = wxString::FromUTF8( msg.value( "mode", "agent" ) );
            if( m_modeChangedCallback )
            {
                m_modeChangedCallback( mode );
            }
        }
        else if( type == wxT( "tab_selected" ) )
        {
            wxString tabId = wxString::FromUTF8( msg.value( "tabId", "" ) );
            if( m_tabSelectedCallback && !tabId.IsEmpty() )
            {
                m_tabSelectedCallback( tabId );
            }
        }
        else if( type == wxT( "tab_close" ) )
        {
            wxString tabId = wxString::FromUTF8( msg.value( "tabId", "" ) );
            if( m_tabCloseCallback && !tabId.IsEmpty() )
            {
                m_tabCloseCallback( tabId );
            }
        }
        else if( type == wxT( "new_tab" ) )
        {
            if( m_newTabCallback )
            {
                m_newTabCallback();
            }
        }
        else if( type == wxT( "history_click" ) )
        {
            if( m_historyClickCallback )
            {
                bool allProjects = msg.value( "allProjects", false );
                m_historyClickCallback( allProjects );
            }
        }
        else if( type == wxT( "history_select" ) )
        {
            wxString conversationId = wxString::FromUTF8( msg.value( "conversationId", "" ) );
            if( m_historySelectCallback && !conversationId.IsEmpty() )
            {
                m_historySelectCallback( conversationId );
            }
        }
        // Plan mode actions
        else if( type == wxT( "plan_approve" ) )
        {
            wxString tabId = wxString::FromUTF8( msg.value( "tabId", "" ) );
            if( m_planApproveCallback )
            {
                m_planApproveCallback( tabId );
            }
        }
        else if( type == wxT( "plan_more_research" ) )
        {
            wxString feedback = wxString::FromUTF8( msg.value( "feedback", "" ) );
            wxString tabId = wxString::FromUTF8( msg.value( "tabId", "" ) );
            if( m_planMoreResearchCallback )
            {
                m_planMoreResearchCallback( feedback, tabId );
            }
        }
        else if( type == wxT( "plan_adjust" ) )
        {
            wxString feedback = wxString::FromUTF8( msg.value( "feedback", "" ) );
            wxString tabId = wxString::FromUTF8( msg.value( "tabId", "" ) );
            if( m_planAdjustCallback )
            {
                m_planAdjustCallback( feedback, tabId );
            }
        }
        else if( type == wxT( "plan_cancel" ) )
        {
            wxString tabId = wxString::FromUTF8( msg.value( "tabId", "" ) );
            if( m_planCancelCallback )
            {
                m_planCancelCallback( tabId );
            }
        }
        else if( type == wxT( "plan_edit_save" ) )
        {
            wxString markdown = wxString::FromUTF8( msg.value( "markdown", "" ) );
            wxString tabId = wxString::FromUTF8( msg.value( "tabId", "" ) );
            if( m_planEditSaveCallback && !markdown.IsEmpty() )
            {
                m_planEditSaveCallback( markdown, tabId );
            }
        }
        else if( type == wxT( "plan_save_to_workspace" ) )
        {
            wxString markdown = wxString::FromUTF8( msg.value( "markdown", "" ) );
            if( m_planSaveToWorkspaceCallback && !markdown.IsEmpty() )
            {
                m_planSaveToWorkspaceCallback( markdown );
            }
        }
        else if( type == wxT( "plan_questions_submit" ) )
        {
            wxString answersJson;
            if( msg.contains( "answers" ) && msg["answers"].is_object() )
                answersJson = wxString::FromUTF8( msg["answers"].dump() );
            else
                answersJson = wxString::FromUTF8( msg.value( "answers", "{}" ) );
            wxString tabId = wxString::FromUTF8( msg.value( "tabId", "" ) );
            if( m_planQuestionsAnswerCallback )
            {
                m_planQuestionsAnswerCallback( answersJson, tabId );
            }
        }
        // Symbol approval actions
        else if( type == wxT( "symbol_approve" ) )
        {
            wxString toolCallId = wxString::FromUTF8( msg.value( "toolCallId", "" ) );
            wxString tabId = wxString::FromUTF8( msg.value( "tabId", "" ) );
            if( m_symbolApproveCallback && !toolCallId.IsEmpty() )
            {
                m_symbolApproveCallback( toolCallId, tabId );
            }
        }
        else if( type == wxT( "symbol_modify" ) )
        {
            wxString toolCallId = wxString::FromUTF8( msg.value( "toolCallId", "" ) );
            wxString feedback = wxString::FromUTF8( msg.value( "feedback", "" ) );
            wxString tabId = wxString::FromUTF8( msg.value( "tabId", "" ) );
            if( m_symbolModifyCallback && !toolCallId.IsEmpty() )
            {
                m_symbolModifyCallback( toolCallId, feedback, tabId );
            }
        }
        else if( type == wxT( "symbol_cancel" ) )
        {
            wxString toolCallId = wxString::FromUTF8( msg.value( "toolCallId", "" ) );
            wxString tabId = wxString::FromUTF8( msg.value( "tabId", "" ) );
            if( m_symbolCancelCallback && !toolCallId.IsEmpty() )
            {
                m_symbolCancelCallback( toolCallId, tabId );
            }
        }
        // Footprint approval actions
        else if( type == wxT( "footprint_approve" ) )
        {
            wxString toolCallId = wxString::FromUTF8( msg.value( "toolCallId", "" ) );
            wxString tabId = wxString::FromUTF8( msg.value( "tabId", "" ) );
            if( m_footprintApproveCallback && !toolCallId.IsEmpty() )
            {
                m_footprintApproveCallback( toolCallId, tabId );
            }
        }
        else if( type == wxT( "footprint_modify" ) )
        {
            wxString toolCallId = wxString::FromUTF8( msg.value( "toolCallId", "" ) );
            wxString feedback = wxString::FromUTF8( msg.value( "feedback", "" ) );
            wxString tabId = wxString::FromUTF8( msg.value( "tabId", "" ) );
            if( m_footprintModifyCallback && !toolCallId.IsEmpty() )
            {
                m_footprintModifyCallback( toolCallId, feedback, tabId );
            }
        }
        else if( type == wxT( "footprint_cancel" ) )
        {
            wxString toolCallId = wxString::FromUTF8( msg.value( "toolCallId", "" ) );
            wxString tabId = wxString::FromUTF8( msg.value( "tabId", "" ) );
            if( m_footprintCancelCallback && !toolCallId.IsEmpty() )
            {
                m_footprintCancelCallback( toolCallId, tabId );
            }
        }
        // BOM approval actions
        else if( type == wxT( "bom_approve" ) )
        {
            wxString toolCallId = wxString::FromUTF8( msg.value( "toolCallId", "" ) );
            wxString tabId = wxString::FromUTF8( msg.value( "tabId", "" ) );
            if( m_bomApproveCallback && !toolCallId.IsEmpty() )
            {
                m_bomApproveCallback( toolCallId, tabId );
            }
        }
        else if( type == wxT( "bom_modify" ) )
        {
            wxString toolCallId = wxString::FromUTF8( msg.value( "toolCallId", "" ) );
            wxString feedback = wxString::FromUTF8( msg.value( "feedback", "" ) );
            wxString tabId = wxString::FromUTF8( msg.value( "tabId", "" ) );
            if( m_bomModifyCallback && !toolCallId.IsEmpty() )
            {
                m_bomModifyCallback( toolCallId, feedback, tabId );
            }
        }
        else if( type == wxT( "bom_cancel" ) )
        {
            wxString toolCallId = wxString::FromUTF8( msg.value( "toolCallId", "" ) );
            wxString tabId = wxString::FromUTF8( msg.value( "tabId", "" ) );
            if( m_bomCancelCallback && !toolCallId.IsEmpty() )
            {
                m_bomCancelCallback( toolCallId, tabId );
            }
        }
        // Auth/payment actions
        else if( type == wxT( "sign_in_click" ) )
        {
            if( m_signInClickCallback )
            {
                m_signInClickCallback();
            }
        }
        else if( type == wxT( "upgrade_click" ) )
        {
            if( m_upgradeClickCallback )
            {
                m_upgradeClickCallback();
            }
        }
        else if( type == wxT( "edit_message" ) )
        {
            wxString messageId = wxString::FromUTF8( msg.value( "messageId", "" ) );
            wxString newContent = wxString::FromUTF8( msg.value( "newContent", "" ) );
            wxString tabId = wxString::FromUTF8( msg.value( "tabId", "" ) );
            if( m_editMessageCallback && !messageId.IsEmpty() && !newContent.IsEmpty() )
            {
                m_editMessageCallback( messageId, newContent, tabId );
            }
        }
        else if( type == wxT( "undo_to_message" ) )
        {
            wxString messageId = wxString::FromUTF8( msg.value( "messageId", "" ) );
            wxString tabId = wxString::FromUTF8( msg.value( "tabId", "" ) );
            if( m_undoToMessageCallback && !messageId.IsEmpty() )
            {
                m_undoToMessageCallback( messageId, tabId );
            }
        }
        else if( type == wxT( "regenerate_message" ) )
        {
            wxString messageId = wxString::FromUTF8( msg.value( "messageId", "" ) );
            wxString tabId = wxString::FromUTF8( msg.value( "tabId", "" ) );
            if( m_regenerateMessageCallback && !messageId.IsEmpty() )
            {
                m_regenerateMessageCallback( messageId, tabId );
            }
        }
    }
    catch( const std::exception& e )
    {
        wxLogDebug( wxT( "Failed to parse bridge message: %s" ), e.what() );
    }
}


wxString CHAT_WEBVIEW_PANEL::EscapeForJS( const wxString& aStr )
{
    wxString result;
    result.reserve( aStr.length() * 2 );
    
    for( wxChar c : aStr )
    {
        switch( c )
        {
        case '\\': result += wxT( "\\\\" ); break;
        case '\'': result += wxT( "\\'" ); break;
        case '"':  result += wxT( "\\\"" ); break;
        case '\n': result += wxT( "\\n" ); break;
        case '\r': result += wxT( "\\r" ); break;
        case '\t': result += wxT( "\\t" ); break;
        case '\0': result += wxT( "\\0" ); break;
        default:
            if( c < 32 )
            {
                result += wxString::Format( wxT( "\\x%02x" ), static_cast<int>( c ) );
            }
            else
            {
                result += c;
            }
            break;
        }
    }
    
    return result;
}


// ============================================================================
// Tab Management
// ============================================================================

void CHAT_WEBVIEW_PANEL::AddTab( const wxString& aId, const wxString& aTitle )
{
    wxString script = wxString::Format(
        wxT( "if(window.kichat){window.kichat.addTab({id:'%s',title:'%s'});}" ),
        EscapeForJS( aId ),
        EscapeForJS( aTitle )
    );
    
    if( m_bridgeReady.load() )
    {
        RunScriptFireAndForget( script );
    }
    else
    {
        m_pendingCommands.push_back( script );
    }
}


void CHAT_WEBVIEW_PANEL::RemoveTab( const wxString& aId )
{
    wxString script = wxString::Format(
        wxT( "if(window.kichat){window.kichat.removeTab('%s');}" ),
        EscapeForJS( aId )
    );
    
    if( m_bridgeReady.load() )
    {
        RunScriptFireAndForget( script );
    }
    else
    {
        m_pendingCommands.push_back( script );
    }
}


void CHAT_WEBVIEW_PANEL::SelectTab( const wxString& aId )
{
    wxString script = wxString::Format(
        wxT( "if(window.kichat){window.kichat.selectTab('%s');}" ),
        EscapeForJS( aId )
    );
    
    if( m_bridgeReady.load() )
    {
        RunScriptFireAndForget( script );
    }
    else
    {
        m_pendingCommands.push_back( script );
    }
}


void CHAT_WEBVIEW_PANEL::ReplaceTabId( const wxString& aOldId, const wxString& aNewId,
                                         const wxString& aTitle )
{
    wxString script = wxString::Format(
        wxT( "if(window.kichat&&window.kichat.replaceTabId){window.kichat.replaceTabId('%s','%s','%s');}" ),
        EscapeForJS( aOldId ),
        EscapeForJS( aNewId ),
        EscapeForJS( aTitle )
    );

    if( m_bridgeReady.load() )
    {
        RunScriptFireAndForget( script );
    }
    else
    {
        m_pendingCommands.push_back( script );
    }
}


void CHAT_WEBVIEW_PANEL::SetTabTitle( const wxString& aId, const wxString& aTitle )
{
    wxString script = wxString::Format(
        wxT( "if(window.kichat){window.kichat.setTabTitle('%s','%s');}" ),
        EscapeForJS( aId ),
        EscapeForJS( aTitle )
    );
    
    if( m_bridgeReady.load() )
    {
        RunScriptFireAndForget( script );
    }
    else
    {
        m_pendingCommands.push_back( script );
    }
}


// ============================================================================
// Message Management
// ============================================================================

void CHAT_WEBVIEW_PANEL::AddMessage( const wxString& aId, const wxString& aRole, 
                                      const wxString& aContent,
                                      const std::vector<ChatAttachment>& aAttachments )
{
    wxString script;
    
    if( aAttachments.empty() )
    {
        // No attachments - use simple format
        script = wxString::Format(
            wxT( "if(window.kichat){window.kichat.addMessage({id:'%s',role:'%s',content:'%s'});}" ),
            EscapeForJS( aId ),
            EscapeForJS( aRole ),
            EscapeForJS( aContent )
        );
    }
    else
    {
        // Build attachments JSON array
        wxString attachmentsJson = wxT( "[" );
        for( size_t i = 0; i < aAttachments.size(); i++ )
        {
            if( i > 0 )
                attachmentsJson += wxT( "," );
            
            const ChatAttachment& att = aAttachments[i];
            attachmentsJson += wxString::Format(
                wxT( "{name:'%s',type:'%s',data:'%s',size:%zu}" ),
                EscapeForJS( att.name ),
                EscapeForJS( att.mimeType ),
                EscapeForJS( att.base64Data ),
                att.size
            );
        }
        attachmentsJson += wxT( "]" );
        
        script = wxString::Format(
            wxT( "if(window.kichat){window.kichat.addMessage({id:'%s',role:'%s',content:'%s',attachments:%s});}" ),
            EscapeForJS( aId ),
            EscapeForJS( aRole ),
            EscapeForJS( aContent ),
            attachmentsJson
        );
    }
    
    if( m_bridgeReady.load() )
    {
        RunScriptFireAndForget( script );
    }
    else
    {
        m_pendingCommands.push_back( script );
    }
}


void CHAT_WEBVIEW_PANEL::AppendToMessage( const wxString& aId, const wxString& aText )
{
    wxString script = wxString::Format(
        wxT( "if(window.kichat){window.kichat.appendToMessage('%s','%s');}" ),
        EscapeForJS( aId ),
        EscapeForJS( aText )
    );
    RunScriptFireAndForget( script );
}


void CHAT_WEBVIEW_PANEL::FinalizeMessage( const wxString& aId )
{
    wxString script = wxString::Format(
        wxT( "if(window.kichat){window.kichat.finalizeMessage('%s');}" ),
        EscapeForJS( aId )
    );
    RunScriptFireAndForget( script );
}


void CHAT_WEBVIEW_PANEL::ClearMessages( const wxString& aConversationId )
{
    wxString script;

    if( aConversationId.IsEmpty() )
        script = wxT( "if(window.kichat){window.kichat.clearMessages();}" );
    else
        script = wxString::Format(
            wxT( "if(window.kichat){window.kichat.clearMessages('%s');}" ),
            EscapeForJS( aConversationId ) );

    if( m_bridgeReady.load() )
    {
        RunScriptFireAndForget( script );
    }
    else
    {
        m_pendingCommands.push_back( script );
    }
}


// ============================================================================
// Indicators
// ============================================================================

void CHAT_WEBVIEW_PANEL::ShowTypingIndicator()
{
    RunScriptFireAndForget( wxT( "if(window.kichat){window.kichat.showTypingIndicator();}" ) );
}


void CHAT_WEBVIEW_PANEL::HideTypingIndicator()
{
    RunScriptFireAndForget( wxT( "if(window.kichat){window.kichat.hideTypingIndicator();}" ) );
}


void CHAT_WEBVIEW_PANEL::ShowStatus( const wxString& aStatus, bool aIsIdle )
{
    wxString script = wxString::Format(
        wxT( "if(window.kichat){window.kichat.showStatus('%s',undefined,%s);}" ),
        EscapeForJS( aStatus ),
        aIsIdle ? wxT( "true" ) : wxT( "false" )
    );
    RunScriptFireAndForget( script );
}


void CHAT_WEBVIEW_PANEL::HideStatus()
{
    RunScriptFireAndForget( wxT( "if(window.kichat){window.kichat.hideStatus();}" ) );
}


void CHAT_WEBVIEW_PANEL::ShowThinking( const wxString& aContent, const wxString& aAgentId )
{
    wxString script;
    if( aAgentId.IsEmpty() )
    {
        script = wxString::Format(
            wxT( "if(window.kichat){window.kichat.showThinking('%s');}" ),
            EscapeForJS( aContent )
        );
    }
    else
    {
        script = wxString::Format(
            wxT( "if(window.kichat){window.kichat.showThinking('%s','%s');}" ),
            EscapeForJS( aContent ), EscapeForJS( aAgentId )
        );
    }
    RunScriptFireAndForget( script );
}


void CHAT_WEBVIEW_PANEL::HideThinking()
{
    RunScriptFireAndForget( wxT( "if(window.kichat){window.kichat.hideThinking();}" ) );
}


void CHAT_WEBVIEW_PANEL::ShowToolCall( const wxString& aToolName, const wxString& aStatusText )
{
    wxString script = wxString::Format(
        wxT( "if(window.kichat){window.kichat.showToolCall('%s','%s');}" ),
        EscapeForJS( aToolName ), EscapeForJS( aStatusText )
    );
    RunScriptFireAndForget( script );
}


void CHAT_WEBVIEW_PANEL::ShowFileEdit( const wxString& aFilename, const wxString& aOldContent,
                                        const wxString& aNewContent )
{
    wxString script = wxString::Format(
        wxT( "if(window.kichat){window.kichat.showFileEdit('%s','%s','%s');}" ),
        EscapeForJS( aFilename ), EscapeForJS( aOldContent ), EscapeForJS( aNewContent )
    );
    RunScriptFireAndForget( script );
}


// ============================================================================
// UI State
// ============================================================================

void CHAT_WEBVIEW_PANEL::SetTheme( bool aIsDark )
{
    wxString script = wxString::Format(
        wxT( "if(window.kichat){window.kichat.setTheme(%s);}" ),
        aIsDark ? wxT( "true" ) : wxT( "false" )
    );
    RunScriptFireAndForget( script );
}


void CHAT_WEBVIEW_PANEL::SetMode( const wxString& aMode )
{
    wxString script = wxString::Format(
        wxT( "if(window.kichat){window.kichat.setMode('%s');}" ),
        EscapeForJS( aMode )
    );
    RunScriptFireAndForget( script );
}


void CHAT_WEBVIEW_PANEL::SetInputEnabled( bool aEnabled )
{
    wxString script = wxString::Format(
        wxT( "if(window.kichat){window.kichat.setInputEnabled(%s);}" ),
        aEnabled ? wxT( "true" ) : wxT( "false" )
    );
    RunScriptFireAndForget( script );
}


void CHAT_WEBVIEW_PANEL::SetInputPlaceholder( const wxString& aPlaceholder )
{
    wxString script = wxString::Format(
        wxT( "if(window.kichat){window.kichat.setInputPlaceholder('%s');}" ),
        EscapeForJS( aPlaceholder )
    );
    RunScriptFireAndForget( script );
}


void CHAT_WEBVIEW_PANEL::SetStreaming( bool aIsStreaming, const wxString& aTabId )
{
    wxString script;
    if( aTabId.IsEmpty() )
    {
        script = wxString::Format(
            wxT( "if(window.kichat){window.kichat.setStreaming(%s);}" ),
            aIsStreaming ? wxT( "true" ) : wxT( "false" )
        );
    }
    else
    {
        script = wxString::Format(
            wxT( "if(window.kichat){window.kichat.setStreaming(%s,'%s');}" ),
            aIsStreaming ? wxT( "true" ) : wxT( "false" ),
            EscapeForJS( aTabId )
        );
    }
    RunScriptFireAndForget( script );
}


void CHAT_WEBVIEW_PANEL::ShowHistoryMenu( const wxString& aConversationsJson )
{
    wxString script = wxString::Format(
        wxT( "if(window.kichat){window.kichat.showHistoryMenu(%s);}" ),
        aConversationsJson
    );
    RunScriptFireAndForget( script );
}


// ============================================================================
// Plan Mode
// ============================================================================

void CHAT_WEBVIEW_PANEL::ShowPhaseIndicator( const wxString& aLabel, const wxString& aColor )
{
    wxString script = wxString::Format(
        wxT( "if(window.kichat){window.kichat.showPhaseIndicator('%s','%s');}" ),
        EscapeForJS( aLabel ),
        EscapeForJS( aColor )
    );
    RunScriptFireAndForget( script );
}


void CHAT_WEBVIEW_PANEL::HidePhaseIndicator()
{
    RunScriptFireAndForget( wxT( "if(window.kichat){window.kichat.hidePhaseIndicator();}" ) );
}


void CHAT_WEBVIEW_PANEL::ShowPlanApproval()
{
    RunScriptFireAndForget( wxT( "if(window.kichat){window.kichat.showPlanApproval();}" ) );
}


void CHAT_WEBVIEW_PANEL::HidePlanApproval()
{
    RunScriptFireAndForget( wxT( "if(window.kichat){window.kichat.hidePlanApproval();}" ) );
}


void CHAT_WEBVIEW_PANEL::ShowPlanQuestions( const wxString& aQuestionsJson )
{
    wxString script = wxString::Format(
        wxT( "if(window.kichat){window.kichat.showPlanQuestions('%s');}" ),
        EscapeForJS( aQuestionsJson )
    );
    RunScriptFireAndForget( script );
}


void CHAT_WEBVIEW_PANEL::HidePlanQuestions()
{
    RunScriptFireAndForget( wxT( "if(window.kichat){window.kichat.hidePlanQuestions();}" ) );
}


void CHAT_WEBVIEW_PANEL::SetPlanDocument( const wxString& aMessageId, const wxString& aMarkdown,
                                           const wxString& aRenderMode )
{
    wxString script = wxString::Format(
        wxT( "if(window.kichat){window.kichat.setPlanDocument('%s','%s','%s');}" ),
        EscapeForJS( aMessageId ),
        EscapeForJS( aMarkdown ),
        EscapeForJS( aRenderMode )
    );
    RunScriptFireAndForget( script );
}


// ============================================================================
// Symbol Preview
// ============================================================================

void CHAT_WEBVIEW_PANEL::ShowSymbolPreview( const wxString& aMessageId,
                                             const wxString& aSymbolJson,
                                             const wxString& aToolCallId )
{
    wxString script = wxString::Format(
        wxT( "if(window.kichat&&window.kichat.showSymbolPreview){"
             "window.kichat.showSymbolPreview('%s','%s','%s');}" ),
        EscapeForJS( aMessageId ),
        EscapeForJS( aSymbolJson ),
        EscapeForJS( aToolCallId )
    );
    RunScriptFireAndForget( script );
}


void CHAT_WEBVIEW_PANEL::ShowSymbolApproval()
{
    RunScriptFireAndForget(
        wxT( "if(window.kichat&&window.kichat.showSymbolApproval){"
             "window.kichat.showSymbolApproval();}" ) );
}


void CHAT_WEBVIEW_PANEL::HideSymbolApproval()
{
    RunScriptFireAndForget(
        wxT( "if(window.kichat&&window.kichat.hideSymbolApproval){"
             "window.kichat.hideSymbolApproval();}" ) );
}


void CHAT_WEBVIEW_PANEL::ShowFootprintPreview( const wxString& aMessageId,
                                                const wxString& aFootprintJson,
                                                const wxString& aToolCallId )
{
    wxString script = wxString::Format(
        wxT( "if(window.kichat&&window.kichat.showFootprintPreview){"
             "window.kichat.showFootprintPreview('%s','%s','%s');}" ),
        EscapeForJS( aMessageId ),
        EscapeForJS( aFootprintJson ),
        EscapeForJS( aToolCallId )
    );
    RunScriptFireAndForget( script );
}


void CHAT_WEBVIEW_PANEL::ShowFootprintApproval()
{
    RunScriptFireAndForget(
        wxT( "if(window.kichat&&window.kichat.showFootprintApproval){"
             "window.kichat.showFootprintApproval();}" ) );
}


void CHAT_WEBVIEW_PANEL::HideFootprintApproval()
{
    RunScriptFireAndForget(
        wxT( "if(window.kichat&&window.kichat.hideFootprintApproval){"
             "window.kichat.hideFootprintApproval();}" ) );
}


// ============================================================================
// BOM Preview
// ============================================================================

void CHAT_WEBVIEW_PANEL::ShowBomPreview( const wxString& aMessageId,
                                          const wxString& aBomJson,
                                          const wxString& aToolCallId )
{
    wxString script = wxString::Format(
        wxT( "if(window.kichat&&window.kichat.showBomPreview){"
             "window.kichat.showBomPreview('%s','%s','%s');}" ),
        EscapeForJS( aMessageId ),
        EscapeForJS( aBomJson ),
        EscapeForJS( aToolCallId )
    );
    RunScriptFireAndForget( script );
}


void CHAT_WEBVIEW_PANEL::ShowBomApproval()
{
    RunScriptFireAndForget(
        wxT( "if(window.kichat&&window.kichat.showBomApproval){"
             "window.kichat.showBomApproval();}" ) );
}


void CHAT_WEBVIEW_PANEL::HideBomApproval()
{
    RunScriptFireAndForget(
        wxT( "if(window.kichat&&window.kichat.hideBomApproval){"
             "window.kichat.hideBomApproval();}" ) );
}


// ============================================================================
// Todos
// ============================================================================

void CHAT_WEBVIEW_PANEL::SetTodos( const wxString& aTodosJson, const wxString& aTabId )
{
    wxString script;
    if( aTabId.IsEmpty() )
    {
        script = wxString::Format(
            wxT( "if(window.kichat){window.kichat.setTodos(%s);}" ),
            aTodosJson
        );
    }
    else
    {
        script = wxString::Format(
            wxT( "if(window.kichat){window.kichat.setTodos(%s,'%s');}" ),
            aTodosJson,
            EscapeForJS( aTabId )
        );
    }
    RunScriptFireAndForget( script );
}


// ============================================================================
// Selected Components Context
// ============================================================================

void CHAT_WEBVIEW_PANEL::SetSelectedComponents( const wxString& aComponentsJson )
{
    wxString script = wxString::Format(
        wxT( "if(window.kichat){window.kichat.setSelectedComponents(%s);}" ),
        aComponentsJson
    );
    RunScriptFireAndForget( script );
}


// ============================================================================
// Auth/Payment
// ============================================================================

void CHAT_WEBVIEW_PANEL::SetAuthState( bool aIsAuthenticated )
{
    wxString script = wxString::Format(
        wxT( "if(window.kichat){window.kichat.setAuthState(%s);}" ),
        aIsAuthenticated ? wxT( "true" ) : wxT( "false" )
    );

    if( m_bridgeReady.load() )
    {
        RunScriptFireAndForget( script );
    }
    else
    {
        m_pendingCommands.push_back( script );
    }
}


void CHAT_WEBVIEW_PANEL::SetUserInfo( const wxString& aName, const wxString& aEmail )
{
    wxString script = wxString::Format(
        wxT( "if(window.kichat&&window.kichat.setUserInfo){window.kichat.setUserInfo('%s','%s');}" ),
        EscapeForJS( aName ),
        EscapeForJS( aEmail )
    );

    if( m_bridgeReady.load() )
    {
        RunScriptFireAndForget( script );
    }
    else
    {
        m_pendingCommands.push_back( script );
    }
}


void CHAT_WEBVIEW_PANEL::ShowBanner( const wxString& aMessage, bool aShowUpgrade )
{
    wxString script = wxString::Format(
        wxT( "if(window.kichat){window.kichat.showBanner('%s',%s);}" ),
        EscapeForJS( aMessage ),
        aShowUpgrade ? wxT( "true" ) : wxT( "false" )
    );

    if( m_bridgeReady.load() )
    {
        RunScriptFireAndForget( script );
    }
    else
    {
        m_pendingCommands.push_back( script );
    }
}


void CHAT_WEBVIEW_PANEL::HideBanner()
{
    wxString script = wxT( "if(window.kichat){window.kichat.hideBanner();}" );

    if( m_bridgeReady.load() )
    {
        RunScriptFireAndForget( script );
    }
    else
    {
        m_pendingCommands.push_back( script );
    }
}


wxString CHAT_WEBVIEW_PANEL::GetChatUIHtml()
{
#ifdef CHAT_UI_BUILT
    // Use the built React app from npm run build
    return GetBuiltChatUIHtml();
#else
    // Fallback HTML when React app hasn't been built
    // This provides basic functionality without the full React UI
    
    return wxT( R"HTML(
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>KiCad Chat</title>
    <style>
        :root {
            --bg-primary: #ffffff;
            --bg-secondary: #f5f5f7;
            --text-primary: #1d1d1f;
            --text-secondary: #6e6e73;
            --accent-color: #007aff;
            --user-bubble-bg: #007aff;
            --user-bubble-text: #ffffff;
            --assistant-bubble-bg: #f0f0f5;
            --assistant-bubble-text: #1d1d1f;
            --border-color: #d2d2d7;
        }
        [data-theme="dark"] {
            --bg-primary: #1e1e1e;
            --bg-secondary: #2d2d2d;
            --text-primary: #f5f5f7;
            --text-secondary: #a1a1a6;
            --accent-color: #0a84ff;
            --user-bubble-bg: #0a84ff;
            --user-bubble-text: #ffffff;
            --assistant-bubble-bg: #3a3a3c;
            --assistant-bubble-text: #f5f5f7;
            --border-color: #48484a;
        }
        * { margin: 0; padding: 0; box-sizing: border-box; }
        html, body { height: 100%; width: 100%; overflow: hidden; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            font-size: 14px;
            background-color: var(--bg-primary);
            color: var(--text-primary);
        }
        .chat-container {
            display: flex;
            flex-direction: column;
            height: 100%;
        }
        .tab-bar {
            display: flex;
            align-items: center;
            height: 40px;
            background-color: var(--bg-secondary);
            border-bottom: 1px solid var(--border-color);
            padding: 0 8px;
        }
        .tab-bar-text {
            font-size: 12px;
            color: var(--text-secondary);
        }
        .message-list {
            flex: 1;
            overflow-y: auto;
            padding: 16px;
        }
        .empty-state {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100%;
            color: var(--text-secondary);
        }
        .empty-state-icon { font-size: 48px; margin-bottom: 16px; opacity: 0.5; }
        .empty-state-text { font-size: 16px; font-weight: 500; }
        .message-bubble {
            max-width: 85%;
            margin-bottom: 12px;
            padding: 10px 14px;
            border-radius: 16px;
            word-wrap: break-word;
        }
        .message-bubble.user {
            margin-left: auto;
            background-color: var(--user-bubble-bg);
            color: var(--user-bubble-text);
            border-bottom-right-radius: 4px;
        }
        .message-bubble.assistant {
            margin-right: auto;
            background-color: var(--assistant-bubble-bg);
            color: var(--assistant-bubble-text);
            border-bottom-left-radius: 4px;
        }
        .input-area {
            padding: 12px 16px 16px;
            background-color: var(--bg-primary);
            border-top: 1px solid var(--border-color);
        }
        .input-row {
            display: flex;
            align-items: flex-end;
            gap: 8px;
        }
        .input-wrapper {
            flex: 1;
        }
        .input-wrapper textarea {
            width: 100%;
            min-height: 40px;
            padding: 10px 14px;
            border: 1px solid var(--border-color);
            border-radius: 20px;
            background-color: var(--bg-primary);
            color: var(--text-primary);
            font-family: inherit;
            font-size: 14px;
            resize: none;
            outline: none;
        }
        .send-button {
            width: 40px;
            height: 40px;
            border: none;
            border-radius: 50%;
            background-color: var(--accent-color);
            color: white;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <div class="chat-container">
        <div class="tab-bar">
            <span class="tab-bar-text">Chat UI loading... (React build required)</span>
        </div>
        <div class="message-list">
            <div class="empty-state">
                <div class="empty-state-icon">⚠️</div>
                <div class="empty-state-text">React UI not built</div>
                <div style="margin-top: 8px; font-size: 13px;">Run 'npm run build' in resources/chat-ui/</div>
            </div>
        </div>
        <div class="input-area">
            <div class="input-row">
                <div class="input-wrapper">
                    <textarea placeholder="Chat UI requires React build..." disabled></textarea>
                </div>
                <button class="send-button" disabled>→</button>
            </div>
        </div>
    </div>
    <script>
        // Minimal bridge for fallback mode
        window.kichat = {
            addTab: function() {},
            removeTab: function() {},
            selectTab: function() {},
            setTabTitle: function() {},
            addMessage: function() {},
            appendToMessage: function() {},
            finalizeMessage: function() {},
            showTypingIndicator: function() {},
            hideTypingIndicator: function() {},
            showStatus: function() {},
            hideStatus: function() {},
            setTheme: function(isDark) {
                document.documentElement.setAttribute('data-theme', isDark ? 'dark' : 'light');
            },
            clearMessages: function() {},
            setMode: function() {},
            setInputEnabled: function() {},
            setInputPlaceholder: function() {},
            showHistoryMenu: function() {},
            // Plan mode methods
            showPhaseIndicator: function() {},
            hidePhaseIndicator: function() {},
            showPlanApproval: function() {},
            hidePlanApproval: function() {},
            setPlanDocument: function() {},
            // Todo methods
            setTodos: function() {},
            // Auth/payment methods
            setAuthState: function() {},
            showBanner: function() {},
            hideBanner: function() {}
        };
        
        // Send bridge ready signal
        function sendBridgeReady() {
            var msg = JSON.stringify({ type: 'send_message', content: '__BRIDGE_READY__' });
            if (window.webkit && window.webkit.messageHandlers && window.webkit.messageHandlers.kicad) {
                window.webkit.messageHandlers.kicad.postMessage(msg);
            } else if (window.chrome && window.chrome.webview) {
                window.chrome.webview.postMessage(msg);
            } else if (window.external && window.external.invoke) {
                window.external.invoke(msg);
            }
        }
        setTimeout(sendBridgeReady, 100);
    </script>
</body>
</html>
)HTML" );
#endif
}
