# GenerateChatUIHeader.cmake
# Converts the built React chat UI HTML into a C++ header file
#
# Input variables:
#   INPUT_FILE  - Path to the built index.html
#   OUTPUT_FILE - Path to the output header file

if( NOT EXISTS "${INPUT_FILE}" )
    message( FATAL_ERROR "Chat UI build output not found: ${INPUT_FILE}" )
endif()

# Read the HTML file
file( READ "${INPUT_FILE}" HTML_CONTENT )

# Escape special characters for C++ raw string literal
# We use R"CHATUI(...)CHATUI" delimiter to avoid issues with quotes
string( REPLACE "\\" "\\\\" HTML_CONTENT "${HTML_CONTENT}" )

# MSVC has a string literal limit of 16,380 characters (C2026 error)
# On Windows, we need to split the content into smaller chunks
# GCC/Clang don't have this limitation
if( WIN32 )
    # Split content into chunks of ~15000 characters to stay safely under MSVC limit
    set( CHUNK_SIZE 15000 )
    string( LENGTH "${HTML_CONTENT}" CONTENT_LENGTH )
    
    # Build the chunked string concatenation
    set( CHUNK_CODE "" )
    set( CHUNK_INDEX 0 )
    set( OFFSET 0 )
    
    while( OFFSET LESS CONTENT_LENGTH )
        # Calculate remaining length
        math( EXPR REMAINING "${CONTENT_LENGTH} - ${OFFSET}" )
        
        # Determine this chunk's size
        if( REMAINING LESS CHUNK_SIZE )
            set( THIS_CHUNK_SIZE ${REMAINING} )
        else()
            set( THIS_CHUNK_SIZE ${CHUNK_SIZE} )
        endif()
        
        # Extract the chunk
        string( SUBSTRING "${HTML_CONTENT}" ${OFFSET} ${THIS_CHUNK_SIZE} CHUNK )
        
        # Add to chunk code - each chunk is a separate string literal
        if( CHUNK_INDEX EQUAL 0 )
            string( APPEND CHUNK_CODE "        R\"CHATUI(${CHUNK})CHATUI\"" )
        else()
            string( APPEND CHUNK_CODE "\n        R\"CHATUI(${CHUNK})CHATUI\"" )
        endif()
        
        # Move to next chunk
        math( EXPR OFFSET "${OFFSET} + ${THIS_CHUNK_SIZE}" )
        math( EXPR CHUNK_INDEX "${CHUNK_INDEX} + 1" )
    endwhile()
    
    message( STATUS "Split chat UI HTML into ${CHUNK_INDEX} chunks for MSVC compatibility" )
    
    # Generate the header file with chunked strings (adjacent string literals are concatenated)
    file( WRITE "${OUTPUT_FILE}" 
"/*
 * This file is auto-generated by cmake/GenerateChatUIHeader.cmake
 * Do not edit manually - changes will be overwritten
 *
 * Contains the built React chat UI as an embedded HTML string
 * Note: On Windows/MSVC, the content is split into multiple string literals
 *       to avoid the 16,380 character limit (C2026 error)
 */

#ifndef CHAT_UI_HTML_H
#define CHAT_UI_HTML_H

#include <wx/string.h>

inline wxString GetBuiltChatUIHtml()
{
    // Adjacent raw string literals are concatenated by the compiler
    return wxString::FromUTF8(
${CHUNK_CODE}
    );
}

#define CHAT_UI_BUILT 1

#endif // CHAT_UI_HTML_H
" )

else()
    # Non-Windows: use single string literal (no size limit issues)
    file( WRITE "${OUTPUT_FILE}" 
"/*
 * This file is auto-generated by cmake/GenerateChatUIHeader.cmake
 * Do not edit manually - changes will be overwritten
 *
 * Contains the built React chat UI as an embedded HTML string
 */

#ifndef CHAT_UI_HTML_H
#define CHAT_UI_HTML_H

#include <wx/string.h>

inline wxString GetBuiltChatUIHtml()
{
    return wxString::FromUTF8( R\"CHATUI(${HTML_CONTENT})CHATUI\" );
}

#define CHAT_UI_BUILT 1

#endif // CHAT_UI_HTML_H
" )

endif()

message( STATUS "Generated chat UI header: ${OUTPUT_FILE}" )
